version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:7.0
    container_name: project_form_suite_database
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - project_network

volumes:
  mongo_data:

networks:
  project_network:
    driver: bridge